name: currency_converter
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Use specific, known compatible versions
  firebase_core: ^2.27.0 
  firebase_auth: ^4.17.8
  cloud_firestore: ^4.15.8
  google_sign_in: ^6.2.1

  # Keep other dependencies as they were (or update if needed)
  http: ^1.1.0 
  google_fonts: ^6.1.0
  intl: ^0.18.1
  sqflite: ^2.3.2
  path: ^1.8.3
  provider: ^6.1.1 # Make sure provider is added

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
