// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6jAWP6Capq_gSnx4mrJbSPjXynsvO-BA',
    appId: '1:207748644577:web:eabccab3000933d5b041a0',
    messagingSenderId: '207748644577',
    projectId: 'currencyconverterapp-c7781',
    authDomain: 'currencyconverterapp-c7781.firebaseapp.com',
    storageBucket: 'currencyconverterapp-c7781.firebasestorage.app',
    measurementId: 'G-5V92G41SBM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDP8Ebxtqzykx6AKMNCtLUYzbsB2pIqWkE',
    appId: '1:207748644577:android:807bd87e3889a6bcb041a0',
    messagingSenderId: '207748644577',
    projectId: 'currencyconverterapp-c7781',
    storageBucket: 'currencyconverterapp-c7781.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChbOXn11Pi-pVlWeNzQSV4dJ6fuDXEOfo',
    appId: '1:207748644577:ios:a092d621f09e799eb041a0',
    messagingSenderId: '207748644577',
    projectId: 'currencyconverterapp-c7781',
    storageBucket: 'currencyconverterapp-c7781.firebasestorage.app',
    iosClientId: '207748644577-g9on7o41srpubghtffrmv5rj2246pmu4.apps.googleusercontent.com',
    iosBundleId: 'com.example.currencyConverter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChbOXn11Pi-pVlWeNzQSV4dJ6fuDXEOfo',
    appId: '1:207748644577:ios:a092d621f09e799eb041a0',
    messagingSenderId: '207748644577',
    projectId: 'currencyconverterapp-c7781',
    storageBucket: 'currencyconverterapp-c7781.firebasestorage.app',
    iosClientId: '207748644577-g9on7o41srpubghtffrmv5rj2246pmu4.apps.googleusercontent.com',
    iosBundleId: 'com.example.currencyConverter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD6jAWP6Capq_gSnx4mrJbSPjXynsvO-BA',
    appId: '1:207748644577:web:9e706e922429b231b041a0',
    messagingSenderId: '207748644577',
    projectId: 'currencyconverterapp-c7781',
    authDomain: 'currencyconverterapp-c7781.firebaseapp.com',
    storageBucket: 'currencyconverterapp-c7781.firebasestorage.app',
    measurementId: 'G-X15EJ7ZVRL',
  );

}
